site_name: DevOps Ramp-up
repo_url: https://github.com/pslcorp/DevOps-RampUp
repo_name: pslcorp/DevOps-RampUp

theme:
  favicon: assets/logo.png
  name: material
  palette:
    primary: indigo
    accent: deep purple
  font:
    text: Lato

extra:
    generator: false
    social:
    - icon: fontawesome/brands/github
      link: https://github.com/pslcorp/DevOps-RampUp

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: false

nav:
  - Home: index.md
  - Linux Basic: linux_basics.md
  - Basic concepts to deploy an application: basic_concepts_to_deploy_an_application.md
  - Scripting: scripting.md
  - Source Code Management – SCM: scm.md
  - Cloud Basics:
    - AWS: cloud-basics/aws.md
    - Azure: cloud-basics/azure.md
  - Infrastructure as code – IaC: infrastructure_as_code.md
  - Server configuration management: configuration_management.md
  - CI/CD: ci-cd.md
